sudo: required

services:
  - docker

before_install:
  - docker build -t test-client -f ./client/Dockerfile.dev ./client

script: skip

after_success:
  - docker build -t esblink/client -f ./client/Dockerfile.dev ./client
  - docker build -t esblink/admin -f ./admin/Dockerfile.dev ./admin
  - docker build -t esblink/db -f ./db/Dockerfile.dev ./db
  - docker build -t esblink/proxy -f ./proxy/Dockerfile.dev ./proxy

  # Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push Images
  - docker push esblink/client
  - docker push esblink/admin
  - docker push esblink/db
  - docker push esblink/proxy

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-south-1"
  app: "esblink-cicd"
  env: "EsblinkCicd-env"
  bucket_name: "elasticbeanstalk-eu-south-1-468230665830"
  bucket_path: "cicd"
  on:
    branc: "master"
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
